apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3-server
  namespace: iperf3-benchmark
spec:
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      hostNetwork: true
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ["-s", "-V"]  # Verbose mode enabled with -V
        ports:
          - containerPort: 5201
            hostPort: 5201
