apiVersion: batch/v1
kind: CronJob
metadata:
  name: iperf3-client
  namespace: ${NAMESPACE}
spec:
  schedule: "${IPERF3_SCHEDULE}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iperf3-client
            image: ${DOCKER_REGISTRY}/iperf3-client:latest
            env:
              - name: PG_HOST
                value: "postgres.${NAMESPACE}.svc.cluster.local"
              - name: PG_USER
                value: "${PG_USER}"
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: password
              - name: PG_DB
                value: "${PG_DB}"
              - name: SERVERS
                value: "${IPERF3_SERVER_IPS}"
            command: ["/bin/sh", "-c"]
            args:
              - |
                IFS=',' read -ra ADDR <<< "$SERVERS"
                for server in "${ADDR[@]}"; do
                  echo "Testing server: $server"
                  result=$(iperf3 -c $server -J -V)
                  escaped_result=$(echo "$result" | sed "s/'/''/g")
                  sql="INSERT INTO throughput_data (server, json_output) VALUES ('$server', '$escaped_result');"
                  echo "Running SQL: $sql"
                  PGPASSWORD=$PG_PASSWORD psql -h $PG_HOST -U $PG_USER -d $PG_DB -c "$sql"
                done
          restartPolicy: OnFailure
