apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3-server
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ["-s"]
        ports:
        - containerPort: 5201
          hostPort: 5201
          name: iperf3
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
      hostNetwork: true  # Run in host network to get accurate measurements