apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: iperf3-benchmark
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS throughput_data (
      id SERIAL PRIMARY KEY,
      server VARCHAR(50),
      test_time TIMESTAMP DEFAULT NOW(),
      json_output JSONB
    );
