apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:${POSTGRES_VERSION}
        env:
          - name: POSTGRES_DB
            value: "${PG_DB}"
          - name: POSTGRES_USER
            value: "${PG_USER}"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pgdata
          emptyDir: {}   # For production, use a PersistentVolumeClaim
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
